"use client";
import {
  Mail,
  Award,
  Sparkles,
  Briefcase,
  GraduationCap,
  FileText,
  FileSpreadsheet,
  BookOpen,
  FileSignature,
  Trophy,
  DollarSign,
  Shield,
  Calendar,
  Building2,
  Users,
  Target,
  Settings,
  ClipboardCheck,
  MessageSquare,
  Heart,
  School,
  UserCheck,
  Gift,
  AlertCircle,
  LogOut,
  PartyPopper,
  Star,
  TrendingUp,
  Zap,
} from "lucide-react";
export const iconMap = {
  Mail:Mail,
  Award:Award,
  Sparkles:Sparkles,
  Briefcase:Briefcase,
  GraduationCap:GraduationCap,
  FileText: FileText,

  FileSpreadsheet:FileSpreadsheet,
  BookOpen:BookOpen,
  FileSignature:FileSignature,
  Trophy:Trophy,
  DollarSign:DollarSign,
  Shield:Shield,
  Calendar:Calendar,
  Building2:Building2,
  Users:Users,
  Target:Target,
  Settings:Settings,

  ClipboardCheck:ClipboardCheck,

  MessageSquare:MessageSquare,
  Heart:Heart,
  School:School,
  UserCheck:UserCheck,
  Gift:Gift,

  AlertCircle:AlertCircle,
  LogOut:LogOut,
  PartyPopper:PartyPopper,

  Star:Star,
  TrendingUp:TrendingUp,
  Zap:Zap,
};
export type IconKey = keyof typeof iconMap;
